version: "3.9"

services:
  goapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/.env
    networks:
      - rate-limiter-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - rate-limiter-network

networks:
  rate-limiter-network:
    driver: bridge
